#!/usr/bin/env python3
import argparse
import os
import toml
from colorama import Fore, Style
from i18n_utils import toml_dump

SOURCE_PATH = "i18n/en.toml"


def get_i18n_files():
    file_list = []
    for cur_dir, _, file_names in os.walk("i18n"):
        for fn in file_names:
            if cur_dir == "i18n" and fn == "en.toml":
                continue

            _, ext = os.path.splitext(fn)
            if ext == ".toml":
                file_list.append(os.path.join(cur_dir, fn))

    return file_list


def main(args):
    if not os.path.exists(SOURCE_PATH):
        return

    with open(SOURCE_PATH, mode="r", encoding="utf-8") as f:
        source = toml.load(f)

    for path in get_i18n_files():
        print(Style.DIM + "Processing {}...".format(path) + Style.RESET_ALL)

        with open(path, mode="r", encoding="utf-8") as f:
            override = toml.load(f)

        t = source.copy()
        for k, v in override.items():
            t[k] = v

        with open(path, mode="w", encoding="utf-8") as f:
            toml_dump(t, f)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Apply English i18n file to other languages."
    )
    args = parser.parse_args()
    main(args)
